title: Add support for OpenAPI scan include/exclude classes/packages
type: feature
description: |
  Introduced new configuration properties to include/exclude classes/packages from OpenAPI scanning with following 
  rules : class-level settings take precedence over package-level settings, exclusions take precedence over inclusions 
  and the longest matching rule applies for packages. 
  By default all classes are scanned (allow all, exclude some), except if some inclusions are defined (exclude all, 
  include some).
  
  Added properties: `application.openapi.scan.exclude.packages`, `application.openapi.scan.exclude.classes`, 
  `application.openapi.scan.packages`, `application.openapi.scan.classes`
  
 
